### ISSUE TITLE
[bug] Close the world when connecting

### ISSUE THREAD

**Issue by guobao2333** [tutinoko2048/SocketBE#14]
![Screenshot_2024-09-19-22-29-02-01](https://github.com/user-attachments/assets/71439e38-2962-4a43-8acb-337525f079d4)

Game version: 1.21.22

Only the port and time zone were modified,  
When I connect, the world will be closed directly. Even when re-entering the world, it will be closed again.

**Comment by tutinoko2048** [comment]
Have you disabled the `Require Encrypted Websockets`?
Currently this library doesn't support encryption.

**Comment by guobao2333** [comment]
![Screenshot_2024-09-19-22-54-14-35_5c8300b655012b1930f2e0a7b81bf6a9](https://github.com/user-attachments/assets/56c054ca-c582-468f-b8b9-2a67e9d33643)

It seems that it cannot be disabled...

**Comment by tutinoko2048** [comment]
Leave the world and try again from main menu

**Comment by guobao2333** [comment]
> Leave the world and try again from main menu

This doesn't work, but restarting Minecraft can.
